### ISSUE TITLE
Deep linking to destination in different graph

### ISSUE THREAD

**Issue by nareto** [RafhaanShah/Android-Navigation-Samples#1]
Hello, thanks for this sample project. I'm implementing the BottomNavigation part in my app, and I'm having trouble navigating between navigation in different graphs. For example, I'd like to have a button in the Title Fragment that when clicked:

+ brings the user to a UserProfile Fragment
+ switches the bottom navigation bar to Leaderboard

I thought I could achieve this with deeplinks as mentioned in the README, so I tried putting this in Title.kt:

    button.setOnClickListener {
        val uri =
                Uri.parse("www.example.com/user/someUsername")
        findNavController().navigate(uri)
    }

but when I click it I get this:

        java.lang.IllegalArgumentException: Navigation destination that matches request NavDeepLinkRequest{ uri=www.example.com/user/trustallatoreErgonomico } cannot be found in the navigation graph NavGraph(com.example.navigationsamples:id/home) startDestination={Destination(com.example.navigationsamples:id/titleScreen) label=Home class=com.example.android.navigationsamples.homescreen.Title}

any suggestions on how to solve this?

**Comment by RafhaanShah** [comment]
The title screen only knows about it's own navigation graph - `navigation/home.xml` so it would not know how to handle this DeepLink as it has no knowledge of the DeepLink. The DeepLink is only mentioned in `navigation/main.xml` and `navigation/list.xml`. (also the scheme is important in DeepLinks, you should include the `http://`)

If you did `requireParentFragment().requireParentFragment().findNavController().navigate(Uri.parse("http://www.example.com/user/someUsername"))` (1st `requireParentFragment()` gives the `navHostFragment`, the 2nd one gives the actual `BottomNavFragment`)

then it would handle the DeepLink, but it would only navigate to the default start destination of the `BottomNavFragment`. It would not go into the `UserProfile` fragment because:

If you look at `BottomNavExtensions#setupDeepLinks` it handles the DeepLink based on the intent (which would work for things like navigation through notifications or from other apps), but `navController.navigate()` does not send an intent as far as I can see.

An alternative that could work is:

```
button.setOnClickListener {
	startActivity(Intent(Intent.ACTION_VIEW).apply { 
		data = Uri.parse("http://www.example.com/user/someUsername")
	})
}
```
Because this sends an actual intent.


A better approach could be to add something like this function to `BottomNavExtensions`:
```
fun BottomNavigationView.navigateToDeepLink(
        navGraphIds: List<Int>,
        fragmentManager: FragmentManager,
        containerId: Int,
        uri: Uri
) {
    navGraphIds.forEachIndexed { index, navGraphId ->
        val fragmentTag = getFragmentTag(index)

        val navHostFragment = obtainNavHostFragment(
                fragmentManager,
                fragmentTag,
                navGraphId,
                containerId
        )
        if (navHostFragment.navController.graph.hasDeepLink(uri)
                && selectedItemId != navHostFragment.navController.graph.id) {
            this.selectedItemId = navHostFragment.navController.graph.id
            navHostFragment.navController.navigate(uri)
        }
    }
}
```

You could call this function in the `BottomNavFragment`, and call `BottomNavFragment` from the `TitleFragment`.
I'd suggest something like a shared `viewModel` between the `TitleFragment` and `BottomNavFragment` but I'll leave that up to you 🙂

**Comment by nareto** [comment]
Thanks for the answer! This navigation stuff is kind of over my head at the moment. The solution you propose works, but only sometimes... Sometimes when I call the navigateToDeepLink function (by posting a Uri to a liveData object in a shared view model as you suggest) no navigation happens and I get the the following line in the logs

    I/FragmentNavigator: Ignoring navigate() call: FragmentManager has already saved its state
    
To be precise this is triggerd by the line `navHostFragment.navController.navigate(uri)`.

The first time I call navigateToDeepLink I get this error, then future calls seem to work. Except that when I load a fragment outside of the BottomNavFragment (for example I have a login and settings Fragment that are in the main graph, in which BottomNavFragment is also a destination), then it seems like it gets reset (and again first time I call it doesn't work, then it doesn't). 

This thing is driving me crazy.

**Comment by RafhaanShah** [comment]
That sounds like an issue with your Fragment communication rather than the navigation.

I've added this to `BottomNavFragment`:
```
fun navigateToDeepLink(uri: Uri) {
        requireView().findViewById<BottomNavigationView>(R.id.bottom_nav_view).navigateToDeepLink(
                listOf(R.navigation.home, R.navigation.list, R.navigation.form),
                childFragmentManager,
                R.id.bottom_nav_container,
                uri
        )
    }
```

and this to `Title`
```
view.findViewById<Button>(R.id.about_btn).setOnClickListener {
            (requireParentFragment().requireParentFragment() as BottomNavFragment).navigateToDeepLink(Uri.parse("http://www.example.com/user/someUsername"))
        }
```

and I can't reproduce the behavior you describe. I only suggested the `viewModel` because it's cleaner than `(requireParentFragment().requireParentFragment() as BottomNavFragment)` but there are plenty of other ways to communicate between Fragments that you can try as well 😄

**Comment by nareto** [comment]
Well, I did kind of lie in my previous post 😇 Since I want to navigate to a Fragment in one of the graphs used by BottomNavFragment from a Fragment in the main graph, what I did was have a shared viewModel also with the Main Activity. This would receive an URI, call

           findNavController(R.id.main_activity_fragment_container).navigate(R.id.destination_main_bottomNav)

and then post the URI to the shared view model with BottomNavFragment. 

Now instead I post directly to BottomNavFragment's viewModel, and call this with the URI the observer gets:

        fun navigateToDeepLink(uri: Uri) {
            if (!this.isAdded) {
                (requireActivity() as MainActivity).gotoBottomNav()
            }
            binding.bottomNav.navigateToDeepLink(
                navGraphIds = navGraphIds,
                fragmentManager = childFragmentManager,
                containerId = R.id.bottomnav_fragment_container,
                uri = uri
            )
        }
    
where `gotoBottomNav()` is a function in the MainActivity containing only the line I posted above with findNavController.

Well, for now it seems to be working without hiccups!

This sure feels a bit too complicated though... I wonder if Google will improve the Navigation classes to make this kind of thing easier and less error prone.
